#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ── Wizard-specific setup ─────────────────────────────────────────────────
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$HOME/.config/clasp-real-estate-manager"
ENV_FILE="$STATE_DIR/wizard.env"
CLASP_USER="desktop-clasp-run"
CLASPRC="$HOME/.clasprc.json"
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"

PROJECT_ID=$(node -e 'try{process.stdout.write(require(process.argv[1]).projectId||"")}catch(e){}' "$REPO_DIR/.clasp.json" 2>/dev/null || true)
[[ -n "$PROJECT_ID" ]] || PROJECT_ID="real-estate-manager-sheets"

# _clasprc_field USER FIELD prints one field of a stored clasp credential.
_clasprc_field() {
  node -e '
    const fs=require("fs");
    try{
      const d=JSON.parse(fs.readFileSync(process.argv[1],"utf8"));
      const t=(d.tokens||{})[process.argv[2]]||{};
      process.stdout.write(String(t[process.argv[3]]??""));
    }catch(e){}
  ' "$CLASPRC" "$1" "$2" 2>/dev/null || true
}

banner "Make gen:configs stop expiring every 7 days"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight: check state and back up your credentials"
say "npm run gen:configs and npm run chore both authenticate as:"
note "  the '$CLASP_USER' credential stored in $CLASPRC"
say ""
say "That token expires every 7 days for as long as GCP project '$PROJECT_ID'"
say "has its OAuth consent screen set to External + Testing. This wizard makes"
say "sure it's published to production, then mints a token under that status."
say ""
say "Safe to re-run: it's also the fix if the token is ever revoked."
say ""

if [[ ! -d "$REPO_DIR" ]]; then
  warn "repo not found at $REPO_DIR"; exit 1
fi
cd "$REPO_DIR"
step "Repo: $REPO_DIR"

if [[ ! -f "$CLASPRC" ]]; then
  warn "No $CLASPRC found. You'll be logging in from scratch, which is fine."
else
  BACKUP="$CLASPRC.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$CLASPRC" "$BACKUP"
  chmod 600 "$BACKUP"
  step "Backed up credentials → $BACKUP"
  note "If anything goes sideways, restore with: cp '$BACKUP' '$CLASPRC'"

  OLD_CLIENT_ID=$(_clasprc_field "$CLASP_USER" client_id)
  if [[ -n "$OLD_CLIENT_ID" ]]; then
    CLASP_OLD_CLIENT_ID_PREFIX="${OLD_CLIENT_ID:0:24}"
    step "Existing '$CLASP_USER' credential uses OAuth client: ${CLASP_OLD_CLIENT_ID_PREFIX}…"
    write_env CLASP_OLD_CLIENT_ID_PREFIX "$CLASP_OLD_CLIENT_ID_PREFIX"
    note "Write that prefix down. You'll match it in the console two stages from now."
  else
    warn "No stored credential named '$CLASP_USER' — you'll create it in stage 4."
  fi
fi
say ""
pause "Press Enter to continue"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Publish the OAuth consent screen to production"
say "This is the one setting that causes the weekly expiry. Everything else"
say "in this wizard is just consequences of changing it."
say ""
open_url "https://console.cloud.google.com/auth/audience?project=$PROJECT_ID"
step "Confirm the project selector at the top reads '$PROJECT_ID'."
step "Check 'Publishing status'. If it already reads 'In production', you're"
step "  done here — skip to the confirmation below."
step "If it reads 'Testing': click 'PUBLISH APP', then confirm in the dialog."
say ""
note "Google will NOT ask you to submit for verification to do this. Because your"
note "manifest requests a sensitive scope (auth/spreadsheets), staying unverified"
note "means two things, both harmless for a single-user tool:"
note "  - you'll see a 'Google hasn't verified this app' screen when you log in"
note "  - the app is capped at 100 users; you are 1"
say ""
warn "If the Publish button is greyed out, a required field is missing."
note "Open the 'Branding' tab, fill in app name / user support email / developer"
note "contact email, save, then come back to Audience and publish."
say ""
if ! confirm "Does the publishing status now read 'In production'?"; then
  warn "Stop here. The remaining stages only help once the status is 'In production'."
  note "A token minted under 'Testing' expires in 7 days no matter what else you do."
  note "Re-run this wizard once you've published."
  exit 1
fi
step "Published."
pause "Press Enter to continue"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Rebuild the OAuth client secret file"
say "The console is right: since mid-2025 Google only shows a client secret at"
say "creation time, and there's no download afterwards. You don't need one."
say ""
say "clasp saved both the client_id and the client_secret into ~/.clasprc.json"
say "when you first logged in, and 'login --creds' reads only three fields:"
note "  client_id, client_secret, redirect_uris"
say ""
say "So we rebuild the file locally instead of downloading it. Nothing is"
say "rotated, and your existing OAuth client keeps working."
say ""

CREDS_FILE="$STATE_DIR/client_secret.json"
SECRET_SOURCE="$CLASPRC"
[[ -f "$SECRET_SOURCE" ]] || SECRET_SOURCE="${BACKUP:-}"

RECOVERED_ID=""
if [[ -n "$SECRET_SOURCE" && -f "$SECRET_SOURCE" ]]; then
  set +e
  RECOVERED_ID=$(node -e '
    const fs = require("fs");
    const [src, user, out] = process.argv.slice(1);
    let t = {};
    try {
      t = (JSON.parse(fs.readFileSync(src, "utf8")).tokens || {})[user] || {};
    } catch (e) { process.exit(1); }
    if (!t.client_id || !t.client_secret) process.exit(1);
    const keyFile = {
      installed: {
        client_id: t.client_id,
        client_secret: t.client_secret,
        auth_uri: "https://accounts.google.com/o/oauth2/auth",
        token_uri: "https://oauth2.googleapis.com/token",
        redirect_uris: ["http://localhost"],
      },
    };
    fs.writeFileSync(out, JSON.stringify(keyFile, null, 2), { mode: 0o600 });
    process.stdout.write(t.client_id);
  ' "$SECRET_SOURCE" "$CLASP_USER" "$CREDS_FILE" 2>/dev/null)
  NODE_STATUS=$?
  set -e
  [[ $NODE_STATUS -eq 0 ]] || RECOVERED_ID=""
fi

if [[ -n "$RECOVERED_ID" ]]; then
  chmod 600 "$CREDS_FILE"
  step "Rebuilt from your stored credential → $CREDS_FILE"
  step "Client: ${RECOVERED_ID:0:24}…"
  note "chmod 600, and deliberately outside the repo: .gitignore has no"
  note "client_secret rule, so a copy in the project is one 'git add .' away"
  note "from being committed."
else
  warn "Couldn't recover a client_secret from $SECRET_SOURCE."
  say ""
  say "Fallback: add a second secret to the existing client. Google allows a"
  say "client to hold more than one, so this does NOT invalidate anything."
  say ""
  open_url "https://console.cloud.google.com/auth/clients?project=$PROJECT_ID"
  step "Click the OAuth 2.0 Client ID of type 'Desktop app' to open it."
  if [[ -n "${CLASP_OLD_CLIENT_ID_PREFIX:-}" ]]; then
    step "Match the one starting: ${CLASP_OLD_CLIENT_ID_PREFIX}…"
  fi
  step "In the 'Client secrets' section, click 'ADD SECRET'."
  step "Copy the new secret NOW — this is the only time it's shown."
  step "Also copy the Client ID from the top of the same page."
  say ""
  note "No Desktop app client listed? Click 'CREATE CLIENT' → Application type:"
  note "'Desktop app' → name it 'clasp run' → Create. You can download the JSON"
  note "at that moment; if you do, just paste its two values here anyway."
  say ""
  ask MANUAL_CLIENT_ID "Paste the Client ID:"
  ask_secret MANUAL_CLIENT_SECRET "Paste the new client secret (hidden):"
  if [[ -z "$MANUAL_CLIENT_ID" || -z "$MANUAL_CLIENT_SECRET" ]]; then
    warn "Both values are required. Re-run the wizard once you have them."
    exit 1
  fi
  MANUAL_CLIENT_ID="$MANUAL_CLIENT_ID" MANUAL_CLIENT_SECRET="$MANUAL_CLIENT_SECRET" \
  node -e '
    const fs = require("fs");
    const keyFile = {
      installed: {
        client_id: process.env.MANUAL_CLIENT_ID,
        client_secret: process.env.MANUAL_CLIENT_SECRET,
        auth_uri: "https://accounts.google.com/o/oauth2/auth",
        token_uri: "https://oauth2.googleapis.com/token",
        redirect_uris: ["http://localhost"],
      },
    };
    fs.writeFileSync(process.argv[1], JSON.stringify(keyFile, null, 2), { mode: 0o600 });
  ' "$CREDS_FILE"
  chmod 600 "$CREDS_FILE"
  step "Wrote $CREDS_FILE (chmod 600, outside the repo)."
fi

say ""
say "Checking clasp will accept the file…"
set +e
node -e '
  const fs = require("fs");
  const keyFile = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  const keys = keyFile.installed || keyFile.web;
  if (!keys) throw new Error("no installed/web block");
  if (!keys.client_id || !keys.client_secret) throw new Error("missing client_id or client_secret");
  if (!keys.redirect_uris || keys.redirect_uris.length === 0) throw new Error("Invalid redirect URL");
  if (!keys.redirect_uris.find(u => new URL(u).hostname === "localhost")) {
    throw new Error("No localhost redirect URL found");
  }
' "$CREDS_FILE"
PARSE_STATUS=$?
set -e
if (( PARSE_STATUS != 0 )); then
  warn "clasp would reject this file. Re-run the wizard and use the manual path."
  exit 1
fi
step "Valid — this replays clasp's own createOauthClient() checks."
write_env CLASP_CREDS_FILE "$CREDS_FILE"
pause "Press Enter to continue"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Re-authorize clasp under the new publishing status"
say "Your current refresh token was issued while the app was in Testing, so it"
say "keeps its 7-day fuse regardless of what you just changed. It has to be"
say "replaced with a token minted now."
say ""
step "Dropping the old '$CLASP_USER' credential (your 'default' clasp login,"
step "  the one 'npm run build' uses for clasp push, is left alone)…"
(cd "$REPO_DIR" && npx clasp -u "$CLASP_USER" logout) >/dev/null 2>&1 || true
say ""
say "A browser window is about to open. In it:"
step "Choose the Google account that owns the spreadsheet."
step "On 'Google hasn't verified this app': click 'Advanced', then"
step "  'Go to $PROJECT_ID (unsafe)'. This is expected — it's your own app."
step "Grant every scope it asks for, then return to this terminal."
say ""
pause "Press Enter to launch the login flow"
say ""

set +e
(cd "$REPO_DIR" && npx clasp -u "$CLASP_USER" login --creds "$CREDS_FILE" --use-project-scopes)
LOGIN_STATUS=$?
set -e

if (( LOGIN_STATUS != 0 )); then
  warn "clasp login exited with status $LOGIN_STATUS."
  note "Common causes: you closed the browser tab, or the redirect port was busy."
  note "Retry by hand from $REPO_DIR:"
  note "  npx clasp -u $CLASP_USER login --creds '$CREDS_FILE' --use-project-scopes"
  exit 1
fi
step "Logged in."
note "--use-project-scopes matters here: it requests the scopes in appsscript.json"
note "(spreadsheets + script.scriptapp), which is what 'clasp run' needs."
pause "Press Enter to continue"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Verify the new grant"
say "First, what clasp now has stored:"
say ""
(cd "$REPO_DIR" && npx clasp -u "$CLASP_USER" show-authorized-user) || warn "show-authorized-user failed"
say ""

NEW_CLIENT_ID=$(_clasprc_field "$CLASP_USER" client_id)
[[ -n "$NEW_CLIENT_ID" ]] && step "Stored client: ${NEW_CLIENT_ID:0:24}…"
say ""
say "Next, an auth probe. It calls clasp run with a function name that does not"
say "exist in src/index.ts, so NOTHING in your spreadsheet is touched — we're"
say "only checking whether the API accepts the token."
say ""
warn "This is the only stage that calls clasp run. It executes no real function."
if confirm "Run the auth probe?"; then
  say ""
  set +e
  PROBE=$( (cd "$REPO_DIR" && npx clasp -u "$CLASP_USER" run --json __wizardAuthProbe__) 2>&1 )
  set -e
  printf '%s\n' "$PROBE" | sed 's/^/    /'
  say ""
  if printf '%s' "$PROBE" | grep -qiE '401|403|PERMISSION_DENIED|invalid_grant|unauthorized|clasp login'; then
    warn "That looks like an auth failure, not a missing-function error."
    note "Re-run stage 4, and double-check the consent screen really says 'In production'."
  else
    step "No auth error — the token was accepted (a 'not found' style error here is"
    step "exactly what we want, since __wizardAuthProbe__ isn't a real function)."
  fi
else
  SKIPPED+=("auth probe (run: npx clasp -u $CLASP_USER run --json __wizardAuthProbe__)")
fi
say ""
pause "Press Enter to continue"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Confirm it's actually permanent"
CHECK_AFTER=$(date -v+8d "+%Y-%m-%d" 2>/dev/null || date -d "+8 days" "+%Y-%m-%d" 2>/dev/null || echo "8 days from now")
write_env CLASP_REAUTHORIZED_ON "$(date +%Y-%m-%d)"
write_env CLASP_VERIFY_AFTER "$CHECK_AFTER"
say ""
say "Nothing you can read locally proves a refresh token is non-expiring — the"
say "expiry lives on Google's side. The real test is time:"
say ""
step "On or after $CHECK_AFTER, run: npm run gen:configs"
step "If it works without a re-login, the 7-day expiry is gone for good."
say ""
say "Ways the token can still die later (none are on a weekly clock):"
note "  - unused for 6 months"
note "  - you revoke access at myaccount.google.com/permissions"
note "  - more than 100 live refresh tokens for this client+account (oldest drops)"
note "  - a Google password change, but only once a Gmail scope is in the grant."
note "    appsscript.json requests spreadsheets + script.scriptapp today, so you're"
note "    clear — note that Gmail IS in enabledAdvancedServices, so the day a"
note "    function actually calls it and a Gmail scope joins the manifest, password"
note "    changes start invalidating this token."
say ""
say "If gen:configs fails later with an auth error, the fix is stage 4 alone:"
note "  cd $REPO_DIR"
note "  npx clasp -u $CLASP_USER login --creds '$CREDS_FILE' --use-project-scopes"
say ""
pause "Press Enter for the summary"

finish
note "Consent screen: $PROJECT_ID is now 'In production'."
note "Client secret kept at: $CREDS_FILE (chmod 600, outside the repo)."
[[ -n "${BACKUP:-}" ]] && note "Old credentials backed up at: $BACKUP"
note "Re-check on $CHECK_AFTER with: npm run gen:configs"
printf '\n'
